# Generated by Django 4.1.6 on 2023-02-07 15:06

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8, message='la longeur doit etre min a 8 ')], verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.models.ValidMail]),
        ),
    ]
