# Generated by Django 4.1.6 on 2023-02-07 15:06

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('person', 'event')},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('eventDate__gte', datetime.datetime(2023, 2, 7, 15, 6, 30, 969317))), name='date invalid'),
        ),
    ]
